version: "3.9"

services:
  fraud-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fraud-service
    env_file: .env
    restart: always
    ports:
      - "${APP_PORT:-8090}:8090"
    networks:
      - payment-service_payment-network

networks:
  payment-service_payment-network:
    external: true